version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - not-reddit

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=root
    - RABBITMQ_DEFAULT_PASS=root
    ports:
      # AMQP protocol port.
      - '5672:5672'
      # HTTP management UI.
      - '15672:15672'

  comment:
    container_name: comment
    build:
      context: ./api
      dockerfile: ./src/main/comment/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - not-reddit

  post:
    container_name: post
    build:
      context: ./api
      dockerfile: ./src/main/post/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8081:8081"
    networks:
      - not-reddit

  user:
    container_name: user
    build:
      context: ./api
      dockerfile: ./src/main/user/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8082:8082"
    networks:
      - not-reddit

networks:
  not-reddit:
