apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api-deployment
  labels:
    app: post-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
      - name: post-api
        image: notreddit.azurecr.io/post-service:latest
        envFrom:
          - secretRef:
              name: cors-secret
          - secretRef:
              name: post-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: post-api-service
spec:
  selector:
    app: post-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
