apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: notreddit.azurecr.io/auth-service:latest
        envFrom:
          - secretRef:
                name: cors-secret
          - secretRef:
              name: auth-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
spec:
  selector:
    app: auth-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
