global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: user-exporter
    static_configs:
      - targets: ["user-exporter-service:9187"]
  - job_name: post-exporter
    static_configs:
      - targets: ["post-exporter-service:9187"]
  - job_name: comment-exporter
    static_configs:
      - targets: ["comment-exporter-service:9187"]
  - job_name: vote-exporter
    static_configs:
      - targets: ["vote-exporter-service:9187"]
