apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  replicas: 1
  image: notreddit.azurecr.io/rabbitmq:3-management
  rabbitmq:
    additionalConfig: |
      default_user=<user>
      default_pass=<pass>
