apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: notreddit.azurecr.io/ui-service
        envFrom:
          - secretRef:
              name: ui-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
