apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-deployment
  labels:
    app: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
      - name: gateway-api
        image: notreddit.azurecr.io/gateway-service
        envFrom:
          - secretRef:
              name: gateway-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_not-reddit_not-reddit-cluster_switzerlandnorth
spec:
  loadBalancerIP: 20.208.62.235
  selector:
    app: gateway-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
