apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-deployment
  labels:
    app: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
      - name: gateway-api
        image: notreddit.azurecr.io/gateway-service:latest
        envFrom:
          - secretRef:
              name: gateway-api-secret
        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "12m"
            memory: "8Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-service
spec:
  selector:
    app: gateway-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-api-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
