apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-exporter-deployment
  namespace: monitoring
  labels:
    app: comment-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-exporter
  template:
    metadata:
      labels:
        app: comment-exporter
    spec:
      containers:
        - name: comment-exporter
          image: prometheuscommunity/postgres-exporter:latest
          envFrom:
            - secretRef:
                name: comment-exporter-secret
---
apiVersion: v1
kind: Service
metadata:
  name: comment-exporter-service
  namespace: monitoring
spec:
  selector:
    app: comment-exporter
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
