version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss
    container_name: meta-research-grafana
    network_mode: host
    environment:
      GF_PLUGIN_ALLOW_LOCAL_MODE: true
    volumes:
      - ./data:/var/data
      - meta-research-grafana:/var/lib/grafana

volumes:
  meta-research-grafana:
