{
 "title": "Meta Platforms Inc. Research Copy",
 "time": { "from": "2017-12-09T03:55:06.732Z", "to": "2023-06-27T09:56:25.619Z" },
 "panels": [
  {
   "title": "Amount of fines issued by Authority",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  authority as Authority,\n  count(Authority) as \"Amount of fines issed from\"\nFROM data.`meta-gdpr-fines`\nGROUP BY Authority\nORDER BY \"Amount of fines issed from\" desc"
    }
   ]
  },
  {
   "title": "Amount of fines issued by Country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  country as Country,\n  count(Country) as \"Amount of fines issed from\"\nFROM data.`meta-gdpr-fines`\nGROUP BY Country\nORDER BY \"Amount of fines issed from\" DESC"
    }
   ]
  },
  {
   "title": "Monetarial amount of fines issued to Meta Platforms, Inc. (in millions of $)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date as time, (fine / 1000000) * 1.08 as \"Fine Amount (in millions of €)\" from data.`meta-gdpr-fines`"
    }
   ]
  },
  {
   "title": "Amount of fines by violation reason",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  violation as Violation,\n  count(Violation) as \"Amount of fines by violation\"\nFROM data.`meta-gdpr-fines`\nGROUP BY Violation"
    }
   ]
  },
  {
   "title": "Volume in millions of shares",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date as time, volume / 1000000 as \"Volume\" FROM data.`meta-stock`"
    }
   ]
  },
  {
   "title": "Stock Price",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT date as time, open as \"Open\", high as \"High\", low as \"Low\", close as \"Close\" FROM data.`meta-stock`"
    }
   ]
  },
  {
   "title": "Amount of violations by article",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT REGEXP_REPLACE(art, \".*(Art\\. [0-9]+).*\", \"$1\") as articl, COUNT(*) AS Amount\nFROM (\n    SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(article, ',', n), ',', -1) as art\n    FROM `meta-gdpr-fines` as t\n    JOIN (\n        SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10\n    ) AS nums\n    ON CHAR_LENGTH(t.article) - CHAR_LENGTH(REPLACE(t.article, ',', '')) >= n - 1\n) AS t\nWHERE art REGEXP 'Art\\\\. [0-9]+'\nGROUP BY articl\nORDER BY Amount DESC;"
    }
   ]
  },
  {
   "title": "Assets of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  date as time,\n  total_assets / 1000 as \"Total Assets\",\n  cash_and_cash_equivalents / 1000 as \"Cash and Cash Equivalents\",\n  marketable_securities / 1000 as \"Marketable Securities\",\n  accounts_receivable_net / 1000 as \"Accounts Receivable Net\",\n  prepaid_expenses_and_other_current_assets / 1000 as \"Prepaid Expenses and Other Current Assets\",\n  total_current_assets / 1000 as \"Total Current Assets\",\n  non_marketable_equity_securities / 1000 as \"Non Marketable Equity Securities\",\n  property_and_equipment_net / 1000 as \"Property and Equipment Net\",\n  operating_lease_right_of_use_assets / 1000 as \"Operating Lease Right of Use Assets\",\n  intangible_assets_net / 1000 as \"Intangible Assets Net\",\n  goodwill / 1000 as \"Goodwill\",\n  other_assets / 1000 as \"Other Assets\"\nFROM `meta-assets`;"
    }
   ]
  },
  {
   "title": "Liabilities of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  date as time,\n  accounts_payable / 1000 as \"Accounts Payable\",\n  partners_payable / 1000 as \"Partners Payable\",\n  operating_lease_liabilities_current / 1000 as \"Operating Lease Liabilities Current\",\n  accrued_expenses_and_other_current_liabilities / 1000 as \"Accrued Expenses and Other Current Liabilities\",\n  total_current_liabilities / 1000 as \"Total Current Liabilities\",\n  operating_lease_liabilities_non_current / 1000 as \"Operating Lease Liabilities Non Current\",\n  long_term_debt / 1000 as \"Long Term Debt\",\n  other_liabilities / 1000 as \"Other Liabilities\",\n  total_liabilities / 1000 as \"Total Liabilities\",\n  additional_paid_in_capital / 1000 as \"Additional Paid In Capital\",\n  accumulated_other_comprehensive_income_loss / 1000 as \"Accumulated Other Comprehensive Income Loss\",\n  retained_earnings / 1000 as \"Retained Earnings\",\n  total_stockholders_equity / 1000 as \"Total Stockholders Equity\",\n  total_liabilities_and_stockholders_equity / 1000 as \"Total Liabilities and Stockholders Equity\"\nFROM `meta-liabilities`;"
    }
   ]
  },
  {
   "title": "Earnings per Share of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\n    date as time,\n    basic as \"Basic\",\n    diluted as \"Diluted\"\nFROM `meta-earnings-per-share`;"
    }
   ]
  },
  {
   "title": "Costs and Expenses of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT date as time,\n    cost_of_revenue / 1000 as \"Cost of Revenue\",\n    research_and_development / 1000 as \"Research and Development\",\n    marketing_and_sales / 1000 as \"Marketing and Sales\",\n    general_and_administrative / 1000 as \"General and Administrative\",\n    total_costs_and_expenses / 1000 as \"Total Costs and Expenses\"\nFROM `meta-costs-and-expenses`;"
    }
   ]
  },
  {
   "title": "Income from Operations of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\n    date as time,\n    income_from_operations / 1000 as \"Income from operations\",\n    family_of_apps / 1000 as \"Family of apps\",\n    reality_labs / 1000 as \"Reality labs\"\nFROM `meta-income-from-operations`;"
    }
   ]
  },
  {
   "title": "Net Income of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\n    date as time,\n    net_income / 1000 as \"Net Income\"\nFROM `meta-net-income`;"
    }
   ]
  },
  {
   "title": "Revenue of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT\n    date as time,\n    total_revenue / 1000 as \"Total Revenue\",\n    advertising / 1000 as \"Advertising\",\n    other_revenue / 1000 as \"Other Revenue\",\n    family_of_apps / 1000 as \"Family of Apps\",\n    reality_labs / 1000 as \"Reality Labs\"\nFROM `meta-revenue`;"
    }
   ]
  },
  {
   "title": "Weighted-average Shares of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT\n    date as time,\n    basic / 1000 as \"Basic\",\n    diluted / 1000 as \"Diluted\"\nFROM `meta-weighted-average-shares`;"
    }
   ]
  },
  {
   "title": "Expenses as a Percentage of Revenue of Meta Platforms, Inc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT date as time, cost_of_revenue as \"Cost of Revenue\", research_and_development as \"Research and Development\", marketing_and_sales as \"Marketing and Sales\", general_and_administrative as \"General and Administrative\"\nFROM `meta-expenses-as-a-percentage-of-revenue`;"
    }
   ]
  },
  {
   "title": "Advertising Revenue by User Geography of Meta Platforms Inc. (in billions of $)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "rawSql": "SELECT date as time,\nus_and_canada/1000 as \"US and Canada\",\neurope/1000 as \"Europe\",\nasia_pacific/1000 as \"Asia Pacific\", rest_of_world/1000 as \"Rest of World\"\nFROM `meta-advertising-revenue-by-user-geography`;"
    }
   ]
  },
  {
   "title": "Facebook Monthly Active Users of Meta Platforms, Inc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "rawSql": "SELECT date as time, us_and_canada/1000 as \"US and Canada\", europe/1000 as \"Europe\", asia_pacific/1000 as \"Asia Pacific\", rest_of_world/1000 as \"Rest of World\"\nFROM `meta-facebook-monthly-active-users`;"
    }
   ]
  },
  {
   "title": "Facebook Daily Active Users of Meta Platforms, Inc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "rawSql": "SELECT date as time, us_and_canada/1000 as \"US and Canada\", europe/1000 as \"Europe\", asia_pacific/1000 as \"Asia Pacific\", rest_of_world/1000 as \"Rest of World\"\nFROM `meta-facebook-daily-active-users`;"
    }
   ]
  },
  {
   "title": "Family Daily Active People of Meta Platforms, Inc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT date as time, daily_active_people as \"Daily Active People\"\nFROM `meta-family-daily-active-people`;"
    }
   ]
  },
  {
   "title": "Family Average Revenue Per Person of Meta Platforms, Inc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT date as time, average_revenue_per_person as \"Average Revenue per Person\"\nFROM `meta-family-average-revenue-per-person`;"
    }
   ]
  },
  {
   "title": "Family Montly Active People of Meta Platforms, Inc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "rawSql": "SELECT date as time, monthly_active_people as \"Monthly Active people\"\nFROM `meta-family-monthly-active-people`;"
    }
   ]
  },
  {
   "title": "Revenue by User Geography of Meta Platforms, Inc.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "rawSql": "SELECT date as time, us_and_canada/1000 AS 'US and Canada', europe/1000 AS 'Europe', asia_pacific/1000 AS 'Asia Pacific', rest_of_world/1000 AS 'Rest of World', total_revenue/1000 AS 'Total Revenue'\nFROM `meta-revenue-by-user-geography`;"
    }
   ]
  }
 ]
}