apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-api-deployment
  labels:
    app: vote-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-api
  template:
    metadata:
      labels:
        app: vote-api
    spec:
      containers:
      - name: vote-api
        image: notreddit.azurecr.io/vote-service:latest
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        envFrom:
          - secretRef:
              name: vote-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vote-api-service
spec:
  selector:
    app: vote-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
