apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-exporter-deployment
  namespace: monitoring
  labels:
    app: vote-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-exporter
  template:
    metadata:
      labels:
        app: vote-exporter
    spec:
      containers:
        - name: vote-exporter
          image: prometheuscommunity/postgres-exporter:latest
          envFrom:
            - secretRef:
                name: vote-exporter-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vote-exporter-service
  namespace: monitoring
spec:
  selector:
    app: vote-exporter
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
