@startuml C4_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "Reddit user")
System_Boundary(c1, "Reddit system") {
    Container(users_api, "Users API", "FastAPI", "API endpoint for registering.")
    Container(comments_api, "Comments API", "FastAPI", "API endpoint for comments.")
    Container(posts_api, "Posts API", "FastAPI", "API endpoint for posts.")
    ContainerDb(postgres_db, "Database", "PostgreSQL", "Holds all information.")
}

Rel(user, users_api, "Uses", "HTTPS")
Rel(user, comments_api, "Uses", "HTTPS")
Rel(user, posts_api, "Uses", "HTTPS")
Rel(users_api, postgres_db, "Reads/Writes", "SQLAlchemy")
Rel(comments_api, postgres_db, "Reads/Writes", "SQLAlchemy")
Rel(posts_api, postgres_db, "Reads/Writes", "SQLAlchemy")
@enduml