name: "Azure Kubernetes Service"

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: azure-kubernetes-service-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            api/src/main/gateway/k8s/gateway-deployment.yml
            api/src/main/user/k8s/user-deployment.yml
            api/src/main/post/k8s/post-deployment.yml
            api/src/main/vote/k8s/vote-deployment.yml
            api/src/main/comment/k8s/comment-deployment.yml
            api/src/main/auth/k8s/auth-deployment.yml
            api/src/main/email/k8s/email-deployment.yml
            api/src/main/award/k8s/award-deployment.yml
            ui/src/main/k8s/ui-deployment.yml

      - name: Rollout restart
        run: |
          kubectl rollout restart deployment user-api-deployment
          kubectl rollout restart deployment post-api-deployment
          kubectl rollout restart deployment vote-api-deployment
          kubectl rollout restart deployment comment-api-deployment
          kubectl rollout restart deployment auth-api-deployment
          kubectl rollout restart deployment email-api-deployment
          kubectl rollout restart deployment gateway-api-deployment
          kubectl rollout restart deployment award-api-deployment
          kubectl rollout restart deployment ui-deployment
