name: Azure Kubernetes Service

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    strategy:
      matrix:
        service:
          # [service-name, deployment-yaml-path]
          - [ gateway, api/src/main/gateway/k8s/deployment.yml ]
          - [ user, api/src/main/user/k8s/deployment.yml ]
          - [ post, api/src/main/post/k8s/deployment.yml ]
          - [ vote, api/src/main/vote/k8s/deployment.yml ]
          - [ comment, api/src/main/comment/k8s/deployment.yml ]
          - [ auth, api/src/main/auth/k8s/deployment.yml ]
          - [ email, api/src/main/email/k8s/deployment.yml ]
          - [ ui, ui/src/main/k8s/deployment.yml ]
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ matrix.service[1] }}
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ matrix.service[0] }}-service:latest
