name: "Pytest"
on: push

jobs:
  pytest:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install -r api/requirements.txt
      - name: Run pytest
        run: |
          cd api/src/test
          pytest
