name: "Shellcheck"
on:
  push:
    paths:
      - "**.sh"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1091
